config/routes.rb
Rails.application.routes.draw do
  
  get 'project_issues/index'

  get 'home1/index'

  get 'meetings/index'

  get 'home/index'

   root 'welcome#index'
   resources :technologies
   resources :user_projects do
	   	member do 
       get :timesheets
	   	end
   end
  resources :tasks
  devise_for :users
	resources :projects
	resources :assign_tasks
	resources :meetings
	resources :timesheets do
		member do
    get :projects
	  end
	end
  
	match '/assign_tasks/complete' => 'assign_tasks#complete', as: 'complete_assign_task', via: :post
	match '/user_projects/complete' => 'user_projects#complete', as: 'complete_user_project', via: :post


	resources :projects do
		resources :tasks
	end


	resources :users do
		resources :projects do
			resources :assign_tasks
		end
	end
  
  resources :projects do
  	resources :project_issues
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assign_task.rb
class AssignTask < ApplicationRecord
	belongs_to :user
	belongs_to :project
	belongs_to :task
	validates_uniqueness_of :task, :scope => [:user_id,:project_id,:task_id]
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/issue.rb
class Issue < ApplicationRecord
	belongs_to :project
end

app/models/meeting.rb
class Meeting < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :technology
  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects
  has_many :tasks, dependent: :destroy
  has_many :assign_tasks, dependent: :destroy
  has_many :issues, dependent: :destroy
  has_many :timesheets, dependent: :destroy

  mount_uploader :image, ImageUploader
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project
end

app/models/technology.rb
class Technology < ApplicationRecord
	has_many :projects
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
	belongs_to :project
	belongs_to :user
	mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :user_projects
    has_many :projects, through: :user_projects
    has_many :assign_tasks
    has_many :timesheets
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :assign_task, dependent: :destroy
  has_one :timesheet
end

app/controllers/assign_tasks_controller.rb
class AssignTasksController < ApplicationController
    def index
    	@user = User.find(params[:user_id])
    	@project = Project.find(params[:project_id])
    	# @task = Task.find(params[:format])
    	@assign_tasks = AssignTask.where(project_id: @project.id, user_id: @user.id)
    end

    def new
    	@user = User.find(params[:user_id])
    	@project = Project.find(params[:project_id])
    	@assign_task = AssignTask.new
    	#@assign_task = @user_project.assign_task.find(params[:id])
    end

    def create
    	@assign_task = AssignTask.new(assign_task_params)
    	@assign_task.save
    	redirect_to assign_tasks_path(project_id: @assign_task.project.id, user_id: @assign_task.user.id)
    end
    	

   def destroy
  	@assign_task = AssignTask.find(params[:id])
    @assign_task.destroy
  	redirect_to assign_tasks_path(project_id: @assign_task.project.id, user_id: @assign_task.user.id)
 
  end

  def complete
		@assign_task = current_user.assign_tasks.find(params[:id])
		@assign_task.completed = true
		@assign_task.save
		redirect_to user_projects_path
	end
    

	private
	def assign_task_params
		params.require(:Assign_task).permit(:task_id, :user_id, :project_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	debugger
    #@assign_task = AssignTask.find(params[:id])
    @home = Home.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assign_tasks_helper.rb
module AssignTasksHelper
end

app/helpers/home1_helper.rb
module Home1Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assign_tasks/index.html.erb
<h3>Project: <b><%= @project.project_name %></b></h3>
<h3>User: <b><%= @user.email %></b></h3>


<h1><b>Assigned Tasks</b></h1>
 
<table class="table table-striped">
  <tr>
    <th>Task</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>

  <% @assign_tasks.each do |a| %>
    <tr>
      
      <td><%= a.task.task_name %></td>
      <td>
          <% if a.completed %>
            completed
          <% else %>
            inprocess
          <% end %>  
      </td>
      <td><%= link_to 'Remove', assign_task_path(a), data: {method: :delete, confirm: "Are you sure to unassign this task?"} %></td>
      


    </tr>
  <% end %>
</table>

<%= link_to 'Back', user_projects_path %>

app/views/assign_tasks/new.html.erb
<p>
  <strong>User_name:</strong>
  <%= @user.email%>
</p>
 
<p>
  <strong>Project_name:</strong>
  <%= @project.project_name %>
</p>

<h2>Tasks</h2>

<% if @assign_task.errors.any? %>
  <ul>
    <% @assign_task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with scope: :Assign_task, url: assign_tasks_path,  local: true do |f| %>  

  <p>
    <%= f.label :task_id %><br>
	  <%= f.collection_select :task_id,  @project.tasks,:id,:task_name, include_blank: true %>
    <%= f.hidden_field :user_id, :value => @user.id%>
    <%= f.hidden_field :project_id, :value => @project.id%>

  </p>

  <p>
	  <%= f.submit %>
  </p>
 
<% end %>

<%= link_to 'Back', user_projects_path %>