config/routes.rb
Rails.application.routes.draw do
  
  get 'project_issues/index'

  get 'home1/index'

  get 'meetings/index'

  get 'home/index'

   root 'welcome#index'
   resources :technologies
   resources :user_projects do
	   	member do 
       get :timesheets
	   	end
   end
  resources :tasks
  devise_for :users
	resources :projects
	resources :assign_tasks
	resources :meetings
	resources :timesheets do
		member do
    get :projects
	  end
	end
  
	match '/assign_tasks/complete' => 'assign_tasks#complete', as: 'complete_assign_task', via: :post
	match '/user_projects/complete' => 'user_projects#complete', as: 'complete_user_project', via: :post


	resources :projects do
		resources :tasks
	end


	resources :users do
		resources :projects do
			resources :assign_tasks
		end
	end
  
  resources :projects do
  	resources :project_issues
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assign_task.rb
class AssignTask < ApplicationRecord
	belongs_to :user
	belongs_to :project
	belongs_to :task
	validates_uniqueness_of :task, :scope => [:user_id,:project_id,:task_id]
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/issue.rb
class Issue < ApplicationRecord
	belongs_to :project
end

app/models/meeting.rb
class Meeting < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :technology
  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects
  has_many :tasks, dependent: :destroy
  has_many :assign_tasks, dependent: :destroy
  has_many :issues, dependent: :destroy
  has_many :timesheets, dependent: :destroy

  mount_uploader :image, ImageUploader
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project
end

app/models/technology.rb
class Technology < ApplicationRecord
	has_many :projects
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
	belongs_to :project
	belongs_to :user
	mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :user_projects
    has_many :projects, through: :user_projects
    has_many :assign_tasks
    has_many :timesheets
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :assign_task, dependent: :destroy
  has_one :timesheet
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	debugger
    #@assign_task = AssignTask.find(params[:id])
    @home = Home.all
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
  	@meeting = Meeting.all
  end

  def new
  	@meeting = Meeting.new
  end

  def create
  	@meeting = Meeting.new(meeting_params)
  	@meeting.save
  	redirect_to meetings_path
  end

  def show
  	@meeting = Meeting.find(params[:id])
  end

  def edit
  	@meeting = Meeting.find(params[:id])
  end

  def update
  	@meeting = Meeting.find(params[:id])
  	debugger
  	@meeting.update(meeting_params)
  	redirect_to meetings_path
  end

  def destroy
  	@meeting = Meeting.find(params[:id])
  	@meeting.destroy
  	redirect_to meetings_path
  end


  private
  	def meeting_params
  		params.require(:meeting).permit(:purpose, :date, :time, :avatar)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assign_tasks_helper.rb
module AssignTasksHelper
end

app/helpers/home1_helper.rb
module Home1Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/meetings/edit.html.erb
<h2>New Meeting</h2>



<%= form_for @meeting, method: :PATCH,local: true do |form| %>  
  <p>
    <%= form.label :purpose %><br>
    <%= form.text_field :purpose %>
  </p>
 
  <p>
    <%= form.label :date %><br>
    <%= form.text_field :date, :id=>'datepicker1' %>
  </p> 

  <p>
    <%= form.label :time %><br>
    <%= form.text_field :time, :id=> 'timepicker1'%>
  </p> 
 

  <p>
    <%= form.submit %>
  </p>

<% end %> 

 

       
 
<script type="text/javascript">
    $(document).ready(function(){
    $('#datepicker1').datepicker();
    $('#timepicker1').timepicker();
    });
</script>
   

app/views/meetings/index.html.erb
<h1>Listing Meetings</h1>
 
<table class="table table-striped">
  <tr>
    <th>Purpose</th>
    <th>Date</th>
    <th>Time</th>
    <th>Document</th>
    <th colspan="3"></th>
  </tr>
 
  <% @meeting.each do |m| %>
    <tr>
      <td><%= m.purpose %></td>
      <td><%= m.date %></td>
      <td><%= m.time %></td>
      <td><%= m.avatar%></td>
    <% if current_user.project_manager %>  
      <td><%= link_to 'Edit', edit_meeting_path(m) %></td>
      <td><%= link_to 'Destroy', meeting_path(m), method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <% end %>

    </tr>
  <% end %>
</table>

<%= link_to 'Back', root_path %> 

app/views/meetings/new.html.erb
<h2>New Meeting</h2>



<%= form_with scope: :meeting, url: meetings_path,  local: true do |form| %>  <p>
    <%= form.label :purpose %><br>
    <%= form.text_field :purpose %>
  </p>
 
  <p>
    <%= form.label :date %><br>
    <%= form.text_field :date, :id=>'datepicker1' %>
  </p> 

  <p>
    <%= form.label :time %><br>
    <%= form.text_field :time, :id=> 'timepicker1'%>
  </p> 


  <p>
    <%= form.label :avatar %><br>
    <%= form.file_field :avatar%>
  </p>  

  <p>
    <%= form.submit %>
  </p>

<% end %> 

 

       
 
<script type="text/javascript">
    $(document).ready(function(){
    $('#datepicker1').datepicker();
    $('#timepicker1').timepicker();
    });
</script>
   

app/views/meetings/show.html.erb
<h1>ABCD</h1>