config/routes.rb
Rails.application.routes.draw do
  
  get 'project_issues/index'

  get 'home1/index'

  get 'meetings/index'

  get 'home/index'

   root 'welcome#index'
   resources :technologies
   resources :user_projects do
	   	member do 
       get :timesheets
	   	end
   end
  resources :tasks
  devise_for :users
	resources :projects
	resources :assign_tasks
	resources :meetings
	resources :timesheets do
		member do
    get :projects
	  end
	end
  
	match '/assign_tasks/complete' => 'assign_tasks#complete', as: 'complete_assign_task', via: :post
	match '/user_projects/complete' => 'user_projects#complete', as: 'complete_user_project', via: :post


	resources :projects do
		resources :tasks
	end


	resources :users do
		resources :projects do
			resources :assign_tasks
		end
	end
  
  resources :projects do
  	resources :project_issues
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assign_task.rb
class AssignTask < ApplicationRecord
	belongs_to :user
	belongs_to :project
	belongs_to :task
	validates_uniqueness_of :task, :scope => [:user_id,:project_id,:task_id]
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/issue.rb
class Issue < ApplicationRecord
	belongs_to :project
end

app/models/meeting.rb
class Meeting < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :technology
  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects
  has_many :tasks, dependent: :destroy
  has_many :assign_tasks, dependent: :destroy
  has_many :issues, dependent: :destroy
  has_many :timesheets, dependent: :destroy

  mount_uploader :image, ImageUploader
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project
end

app/models/technology.rb
class Technology < ApplicationRecord
	has_many :projects
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
	belongs_to :project
	belongs_to :user
	mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :user_projects
    has_many :projects, through: :user_projects
    has_many :assign_tasks
    has_many :timesheets
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :assign_task, dependent: :destroy
  has_one :timesheet
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	debugger
    #@assign_task = AssignTask.find(params[:id])
    @home = Home.all
  end
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController
	def index
		@user_project = UserProject.all
	end

	def new
    @user_project = UserProject.new
	end

	def create
        @user_project = UserProject.new(user_project_params)
        if UserProject.where(project_id: params[:user_project][:project_id], user_id: params[:user_project][:user_id]).first.present?
          flash[:notice] = "Already Assigned!"
          redirect_to user_projects_path
        else
	        @user_project.save
	        redirect_to user_projects_path
	      end
	end

	def show
		@user_project = UserProject.find(params[:id])
	end

	def edit
		@user_project = UserProject.find(params[:id])
	end

	def update
		@user_project = UserProject.find(params[:id])

		if @user_project.update(user_project_params)
          redirect_to @user_project
        else
          render 'edit'
        end
    end

	def destroy
	  @user_project = UserProject.find(params[:id])
      @user_project.destroy
 
      redirect_to user_projects_path
	end

	def timesheets
	  @timesheet = Timesheet.where(project_id: params[:id], user_id: params[:user_id])
	end

	def complete
		debugger
		@timesheet = Timesheet.find(params[:id])
		@timesheet.completed = true
		@timesheet.save
		redirect_to user_projects_path
	end

	private
	def user_project_params
		params.require(:user_project).permit(:user_id, :project_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assign_tasks_helper.rb
module AssignTasksHelper
end

app/helpers/home1_helper.rb
module Home1Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/user_projects/edit.html.erb
<% if current_user.project_manager == true %>

<%= form_for @user_project,  method: :PATCH,local: true do |form| %>  <p>
    <%= form.label :project_id %><br>
    <%= form.collection_select :project_id, Project.all,:id,:project_name, include_blank: true %>
  </p>
 
  <p>
    <%= form.label :user_id %><br>
    <%= form.collection_select :user_id, User.all,:id,:email, include_blank: true %>
  </p> 

 
  <p>
    <%= form.submit %>
  </p>

<% end %>  
<% else %>
<% end %>


<%= link_to 'Back', user_projects_path %>

app/views/user_projects/index.html.erb
<% if current_user.project_manager.present?%>
<h1>Assigned Projects</h1>
 
<table class="table table-striped">
  <tr>
    <th>User Name</th>
    <th>Project Name</th>
    <th colspan="5"></th>
    <th>Timesheet</th>
  </tr>
  <% @user_project.each do |b| %>
    <tr>
      <td><%= b.user.email %></td>
      <td><%= b.project.try(:project_name)  %></td>
     
      
      <td><%= link_to 'Show', user_project_path(b) %></td>
      <td><%= link_to 'Edit', edit_user_project_path(b) %></td>
      <td><%= link_to 'Destroy', user_project_path(b), method: :delete %></td>
      <td><%= link_to 'Assign Task', new_user_project_assign_task_path(b.user.id, b.project.id) %></td>
      <td><%= link_to 'Assigned Tasks', assign_tasks_path(project_id: b.project.id, user_id: b.user.id) %></td>

     <td><%= link_to 'Timesheet', timesheets_user_project_path(b.project.id, user_id: b.user.id)%></td>


    </tr>
  <% end %>
</table>
<% else%>
  <%current_user.projects.each do |project| %>
    <p>

      <h3>Project_name: <b><%= project.project_name %></b></h3>

      <table class="table table-striped">
      <tr>
        <th> <strong>Task_name: </strong></th>
        <th></th>
        <th> <strong>Status: </strong></th>
        <th colspan="3"></th>
      </tr>
      <%current_user.assign_tasks.where(project_id: project.id).each do |assign_task| %>
        <tr> 
          <td><%= assign_task.task.task_name %></td>
          <td>

            <%#= select_tag :assign_task, options_for_select(AssignTask.all.collect {|e| ["#{e.completed} - #{e.inprocess}", e.id] }), :include_blank => true %>

            <%= link_to "Complete", complete_assign_task_path(id: assign_task.id), method: :post %>
              
          </td>




          <td> <% if assign_task.completed %>
            Completed
          <% else %>
            Inprocess
          <% end %></td>
        </tr>

      <% end %>
      </table>
      
    </p>
  <% end %>

 

<% end %>

<%= link_to 'Back', root_path %> 

 

app/views/user_projects/new.html.erb
<% if current_user.project_manager == true %>

<%= form_with scope: :user_project, url: user_projects_path,  local: true do |form| %>  
  <p>
    <%= form.label :project_id %><br>
    <%= form.collection_select :project_id, Project.all,:id,:project_name, include_blank: true %>
  </p>
 
  <p>
    <%= form.label :user_id %><br>
    <%= form.collection_select :user_id, User.all,:id,:email, include_blank: true %>
  </p> 

  

  <p>
    <%= form.submit %>
  </p>

<% end %>  
<% else %>
<% end %>

app/views/user_projects/show.html.erb
<p>
  <strong>User_name:</strong>
  <%= @user_project.user.email%>
</p>
 
<p>
  <strong>Project_name:</strong>
  <%= @user_project.project.project_name %>
</p>



<%= link_to 'Back', user_projects_path %>

app/views/user_projects/timesheets.html.erb
  <% @timesheet.each do |t|%>

  <p>
		<h5>Document: <b><%= t.avatar %></b></h3>
	</p>

	<%end%>