config/routes.rb
Rails.application.routes.draw do
  
  get 'project_issues/index'

  get 'home1/index'

  get 'meetings/index'

  get 'home/index'

   root 'welcome#index'
   resources :technologies
   resources :user_projects do
	   	member do 
       get :timesheets
	   	end
   end
  resources :tasks
  devise_for :users
	resources :projects
	resources :assign_tasks
	resources :meetings
	resources :timesheets do
		member do
    get :projects
	  end
	end
  
	match '/assign_tasks/complete' => 'assign_tasks#complete', as: 'complete_assign_task', via: :post
	match '/user_projects/complete' => 'user_projects#complete', as: 'complete_user_project', via: :post


	resources :projects do
		resources :tasks
	end


	resources :users do
		resources :projects do
			resources :assign_tasks
		end
	end
  
  resources :projects do
  	resources :project_issues
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assign_task.rb
class AssignTask < ApplicationRecord
	belongs_to :user
	belongs_to :project
	belongs_to :task
	validates_uniqueness_of :task, :scope => [:user_id,:project_id,:task_id]
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/issue.rb
class Issue < ApplicationRecord
	belongs_to :project
end

app/models/meeting.rb
class Meeting < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :technology
  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects
  has_many :tasks, dependent: :destroy
  has_many :assign_tasks, dependent: :destroy
  has_many :issues, dependent: :destroy
  has_many :timesheets, dependent: :destroy

  mount_uploader :image, ImageUploader
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project
end

app/models/technology.rb
class Technology < ApplicationRecord
	has_many :projects
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
	belongs_to :project
	belongs_to :user
	mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :user_projects
    has_many :projects, through: :user_projects
    has_many :assign_tasks
    has_many :timesheets
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :assign_task, dependent: :destroy
  has_one :timesheet
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	debugger
    #@assign_task = AssignTask.find(params[:id])
    @home = Home.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	# before_filter :authenticate_user!
 #  after_action :verify_authorized

  def index
  	@project = Project.all
  end

  def new
  	@project = Project.new
  end

  def create
    @project = Project.new(project_params)
   
    if @project.save
      redirect_to project_path(@project)
    else
      render 'new'
    end 
  end

  def show
  	@project = Project.find(params[:id])
  end

  def edit
  	@project = Project.find(params[:id])
  end

  def update
  	 @project = Project.find(params[:id])
 
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
  	@project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private
	  def project_params
	  	params.require(:project).permit(:project_name, :description,:technology_id, :start_date, :end_date, :project_cost)
	  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assign_tasks_helper.rb
module AssignTasksHelper
end

app/helpers/home1_helper.rb
module Home1Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= form_for @project, method: :PATCH,local: true do |form| %>
  <p>
    <%= form.label :project_name %><br>
    <%= form.text_field :project_name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p> 
 
  <p>
    <%= form.label :techonology %><br>
    <%= form.collection_select :technology_id, Technology.order(:technology_name),:id,:technology_name, include_blank: true %>
  </p>

  <p>
    <%= form.label :start_date %><br>
    <%#= form.text_area :start_date %>
    <%= form.text_field :start_date ,:id=>'datepicker1'%>
  </p>
 

 <p>
    <%= form.label :end_date %><br>
   <%= form.text_field :end_date ,:id=>'datepicker'%>
  </p>
 

 <p>
    <%= form.label :project_cost %><br>
    <%= form.text_field :project_cost %>
  </p>
 

 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', root_path %>



<script type="text/javascript">
  $(document).ready(function(){
    $('#datepicker').datepicker();
    $('#datepicker1').datepicker();
  });
</script>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>
 
<table class="table table-striped">
  <tr>
    <th>Project Name</th>
    <th>Description</th>
    <th>Techonology</th>
    <th colspan="4"></th>
  </tr>
 
  <% @project.each do |project| %>
    <tr>
      <td><%= project.project_name %></td>
      <td><%= project.description %></td>
      <td><%= project.technology.technology_name %></td>
      <td><%= link_to 'Show', project_path(project) %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Destroy', project_path(project), method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Issues', project_project_issues_path(project_id: project.id)%></td>        


    </tr>
  <% end %>
</table>

<%= link_to 'Back', root_path %> 

app/views/projects/new.html.erb
<h2>New Project</h2>

<% if @project.errors.any? %>
  <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with scope: :project, url: projects_path,  local: true do |form| %>  <p>
    <%= form.label :project_name %><br>
    <%= form.text_field :project_name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p> 
 
  <p>
    <%= form.label :techonology %><br>
    <%= form.collection_select :technology_id, Technology.order(:technology_name),:id,:technology_name, include_blank: true %>
  </p>

  <p>
    <%= form.label :start_date %><br>
    <%#= form.text_area :start_date %>
    <%= form.text_field :start_date ,:id=>'datepicker1'%>
  </p>
 

 <p>
    <%= form.label :end_date %><br>
   <%= form.text_field :end_date ,:id=>'datepicker'%>
  </p>
 

 <p>
    <%= form.label :project_cost %><br>
    <%= form.text_field :project_cost %>
  </p>
 

 
  <p>
    <%= form.submit :class=>"btn btn-primary" %>
  </p>
<% end %>

<%= link_to 'Back', root_path %>



<script type="text/javascript">
  $(document).ready(function(){
    $('#datepicker').datepicker();
    $('#datepicker1').datepicker();
  });
</script>

app/views/projects/show.html.erb
<p>
  <strong>Project_name:</strong>
  <%= @project.project_name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Techonology:</strong>
  <%= @project.technology.technology_name %>
</p>

<p>
  <strong>Start_date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>End_date:</strong>
  <%= @project.end_date %>
</p>

<p>
  <strong>Project_cost:</strong>
  <%= @project.project_cost %>
</p>


<table class="table table-striped">
  <tr>
    <th><h2><b>Tasks</b></h2></th>
    <th colspan="3"></th>
  </tr>

  <% @project.tasks.each do |a| %>
    <tr>
      <td><%= a.task_name %></td>
      <td><%= link_to 'Destroy', project_task_path(@project, a.id), method: :delete %></td>
    

    </tr>
  <% end %>
</table>


<h2>Add a Task:</h2>
<%= form_with(model: [ @project, @project.tasks.build ], local: true) do |form| %>
  <p>
    <%= form.label :task_name %><br>
    <%= form.text_field :task_name %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', projects_path %>